{
  "name": "{{ name }}",
  "appearance": "{{ mode }}",
  "style": {
    "accents": [
      "{{ accent }}",
      "{{ blue }}",
      "{{ green }}",
      "{{ magenta }}",
      "{{ orange }}",
      "{{ cyan }}",
      "{{ yellow }}",
      "{{ red }}"
    ],

    "background.appearance": "opaque",
    "background": "{{ background }}",
    "surface.background": "{{ dark_background }}",
    "elevated_surface.background": "{{ dark_background }}",

    "border": "{{ muted }}",
    "border.variant": "{{ muted }}",
    "border.focused": "{{ accent }}",
    "border.selected": "{{ accent }}",
    "border.transparent": "#00000000",
    "border.disabled": "{{ muted }}",

    "element.background": "{{ lighter_background }}",
    "element.hover": "{{ selection }}",
    "element.active": "{{ selection }}",
    "element.selected": "{{ selection }}",
    "element.disabled": "{{ dark_background }}",
    "drop_target.background": "{{ accent }}33",

    "ghost_element.background": "#00000000",
    "ghost_element.hover": "{{ selection }}66",
    "ghost_element.active": "{{ selection }}",
    "ghost_element.selected": "{{ selection }}99",
    "ghost_element.disabled": "{{ dark_background }}",

    "text": "{{ foreground }}",
    "text.muted": "{{ dark_foreground }}",
    "text.placeholder": "{{ dark_foreground }}",
    "text.disabled": "{{ muted }}",
    "text.accent": "{{ accent }}",
    "link_text.hover": "{{ accent }}",

    "icon": "{{ foreground }}",
    "icon.muted": "{{ dark_foreground }}",
    "icon.placeholder": "{{ dark_foreground }}",
    "icon.disabled": "{{ muted }}",
    "icon.accent": "{{ accent }}",

    "status_bar.background": "{{ dark_background }}",
    "title_bar.background": "{{ dark_background }}",
    "title_bar.inactive_background": "{{ darker_background }}",
    "toolbar.background": "{{ background }}",
    "tab_bar.background": "{{ darker_background }}",
    "tab.inactive_background": "{{ dark_background }}",
    "tab.active_background": "{{ background }}",

    "panel.background": "{{ dark_background }}",
    "panel.overlay_background": "{{ dark_background }}",
    "panel.focused_border": "{{ accent }}",
    "panel.indent_guide": "{{ muted }}",
    "panel.indent_guide_active": "{{ accent }}",
    "panel.indent_guide_hover": "{{ accent }}",
    "pane.focused_border": "{{ accent }}",
    "pane_group.border": "{{ muted }}",

    "scrollbar.thumb.background": "{{ muted }}66",
    "scrollbar.thumb.hover_background": "{{ muted }}b3",
    "scrollbar.thumb.border": "#00000000",
    "scrollbar.track.background": "#00000000",
    "scrollbar.track.border": "{{ dark_background }}",

    "search.match_background": "{{ accent }}33",

    "editor.foreground": "{{ foreground }}",
    "editor.background": "{{ background }}",
    "editor.gutter.background": "{{ background }}",
    "editor.subheader.background": "{{ dark_background }}",
    "editor.active_line.background": "{{ lighter_background }}80",
    "editor.highlighted_line.background": "{{ selection }}",
    "editor.line_number": "{{ dim }}",
    "editor.active_line_number": "{{ foreground }}",
    "editor.invisible": "{{ muted }}",
    "editor.wrap_guide": "{{ muted }}4d",
    "editor.active_wrap_guide": "{{ muted }}",
    "editor.indent_guide": "{{ muted }}4d",
    "editor.indent_guide_active": "{{ muted }}",
    "editor.document_highlight.bracket_background": "{{ accent }}33",
    "editor.document_highlight.read_background": "{{ accent }}26",
    "editor.document_highlight.write_background": "{{ accent }}33",

    "terminal.background": "{{ background }}",
    "terminal.foreground": "{{ foreground }}",
    "terminal.bright_foreground": "{{ bright_foreground }}",
    "terminal.dim_foreground": "{{ dark_foreground }}",
    "terminal.ansi.background": "{{ background }}",
    "terminal.ansi.black": "{{ color0 }}",
    "terminal.ansi.red": "{{ color1 }}",
    "terminal.ansi.green": "{{ color2 }}",
    "terminal.ansi.yellow": "{{ color3 }}",
    "terminal.ansi.blue": "{{ color4 }}",
    "terminal.ansi.magenta": "{{ color5 }}",
    "terminal.ansi.cyan": "{{ color6 }}",
    "terminal.ansi.white": "{{ color7 }}",
    "terminal.ansi.bright_black": "{{ color8 }}",
    "terminal.ansi.bright_red": "{{ color9 }}",
    "terminal.ansi.bright_green": "{{ color10 }}",
    "terminal.ansi.bright_yellow": "{{ color11 }}",
    "terminal.ansi.bright_blue": "{{ color12 }}",
    "terminal.ansi.bright_magenta": "{{ color13 }}",
    "terminal.ansi.bright_cyan": "{{ color14 }}",
    "terminal.ansi.bright_white": "{{ color15 }}",
    "terminal.ansi.dim_black": "{{ color0 }}",
    "terminal.ansi.dim_red": "{{ color1 }}",
    "terminal.ansi.dim_green": "{{ color2 }}",
    "terminal.ansi.dim_yellow": "{{ color3 }}",
    "terminal.ansi.dim_blue": "{{ color4 }}",
    "terminal.ansi.dim_magenta": "{{ color5 }}",
    "terminal.ansi.dim_cyan": "{{ color6 }}",
    "terminal.ansi.dim_white": "{{ color7 }}",

    "error": "{{ red }}",
    "error.background": "{{ red }}1a",
    "error.border": "{{ red }}4d",
    "warning": "{{ yellow }}",
    "warning.background": "{{ yellow }}1a",
    "warning.border": "{{ yellow }}4d",
    "info": "{{ blue }}",
    "info.background": "{{ blue }}1a",
    "info.border": "{{ blue }}4d",
    "success": "{{ green }}",
    "success.background": "{{ green }}1a",
    "success.border": "{{ green }}4d",
    "hint": "{{ cyan }}",
    "hint.background": "{{ cyan }}1a",
    "hint.border": "{{ cyan }}4d",
    "predictive": "{{ dark_foreground }}",
    "predictive.background": "{{ dark_foreground }}1a",
    "predictive.border": "{{ dark_foreground }}4d",
    "conflict": "{{ orange }}",
    "conflict.background": "{{ orange }}1a",
    "conflict.border": "{{ orange }}4d",
    "created": "{{ green }}",
    "created.background": "{{ green }}1a",
    "created.border": "{{ green }}4d",
    "deleted": "{{ red }}",
    "deleted.background": "{{ red }}1a",
    "deleted.border": "{{ red }}4d",
    "modified": "{{ yellow }}",
    "modified.background": "{{ yellow }}1a",
    "modified.border": "{{ yellow }}4d",
    "renamed": "{{ blue }}",
    "renamed.background": "{{ blue }}1a",
    "renamed.border": "{{ blue }}4d",
    "hidden": "{{ dark_foreground }}",
    "hidden.background": "{{ dark_background }}",
    "hidden.border": "{{ muted }}",
    "ignored": "{{ dark_foreground }}",
    "ignored.background": "{{ dark_background }}",
    "ignored.border": "{{ muted }}",
    "unreachable": "{{ dark_foreground }}",
    "unreachable.background": "{{ dark_background }}",
    "unreachable.border": "{{ muted }}",

    "version_control.added": "{{ green }}",
    "version_control.added_background": "{{ green }}1a",
    "version_control.modified": "{{ yellow }}",
    "version_control.modified_background": "{{ yellow }}1a",
    "version_control.deleted": "{{ red }}",
    "version_control.deleted_background": "{{ red }}1a",
    "version_control.renamed": "{{ blue }}",
    "version_control.conflict": "{{ orange }}",
    "version_control.conflict_background": "{{ orange }}1a",
    "version_control.ignored": "{{ dark_foreground }}",

    "players": [
      { "cursor": "{{ accent }}", "background": "{{ accent }}", "selection": "{{ selection }}" },
      { "cursor": "{{ green }}", "background": "{{ green }}", "selection": "{{ green }}33" },
      { "cursor": "{{ magenta }}", "background": "{{ magenta }}", "selection": "{{ magenta }}33" },
      { "cursor": "{{ orange }}", "background": "{{ orange }}", "selection": "{{ orange }}33" },
      { "cursor": "{{ cyan }}", "background": "{{ cyan }}", "selection": "{{ cyan }}33" },
      { "cursor": "{{ red }}", "background": "{{ red }}", "selection": "{{ red }}33" }
    ],

    "vim.mode.text": "{{ background }}",
    "vim.normal.background": "{{ accent }}",
    "vim.normal.foreground": "{{ background }}",
    "vim.insert.background": "{{ green }}",
    "vim.insert.foreground": "{{ background }}",
    "vim.visual.background": "{{ magenta }}",
    "vim.visual.foreground": "{{ background }}",
    "vim.visual_line.background": "{{ magenta }}",
    "vim.visual_line.foreground": "{{ background }}",
    "vim.visual_block.background": "{{ magenta }}",
    "vim.visual_block.foreground": "{{ background }}",
    "vim.replace.background": "{{ red }}",
    "vim.replace.foreground": "{{ background }}",
    "vim.helix_normal.background": "{{ accent }}",
    "vim.helix_normal.foreground": "{{ background }}",
    "vim.helix_select.background": "{{ cyan }}",
    "vim.helix_select.foreground": "{{ background }}",

    "syntax": {
      "attribute": { "color": "{{ cyan }}" },
      "boolean": { "color": "{{ orange }}" },
      "character": { "color": "{{ green }}" },
      "character.special": { "color": "{{ bright_magenta }}" },
      "comment": { "color": "{{ dim }}", "font_style": "italic" },
      "comment.doc": { "color": "{{ dim }}", "font_style": "italic" },
      "comment.documentation": { "color": "{{ dim }}", "font_style": "italic" },
      "comment.todo": { "color": "{{ orange }}", "font_weight": 700 },
      "comment.warning": { "color": "{{ yellow }}" },
      "comment.error": { "color": "{{ red }}" },
      "comment.note": { "color": "{{ cyan }}" },
      "comment.hint": { "color": "{{ cyan }}" },
      "concept": { "color": "{{ yellow }}" },
      "constant": { "color": "{{ orange }}" },
      "constant.builtin": { "color": "{{ cyan }}" },
      "constant.macro": { "color": "{{ cyan }}" },
      "constructor": { "color": "{{ yellow }}" },
      "diff.plus": { "color": "{{ green }}" },
      "diff.minus": { "color": "{{ red }}" },
      "embedded": { "color": "{{ foreground }}" },
      "emphasis": { "color": "{{ foreground }}", "font_style": "italic" },
      "emphasis.strong": { "color": "{{ foreground }}", "font_weight": 700 },
      "enum": { "color": "{{ yellow }}" },
      "field": { "color": "{{ cyan }}" },
      "float": { "color": "{{ orange }}" },
      "function": { "color": "{{ blue }}" },
      "function.builtin": { "color": "{{ cyan }}" },
      "function.call": { "color": "{{ blue }}" },
      "function.decorator": { "color": "{{ cyan }}", "font_style": "italic" },
      "function.macro": { "color": "{{ cyan }}" },
      "function.method": { "color": "{{ blue }}" },
      "function.method.call": { "color": "{{ blue }}" },
      "hint": { "color": "{{ cyan }}", "font_style": "italic" },
      "keyword": { "color": "{{ bright_magenta }}" },
      "keyword.conditional": { "color": "{{ bright_magenta }}" },
      "keyword.conditional.ternary": { "color": "{{ bright_magenta }}" },
      "keyword.coroutine": { "color": "{{ bright_magenta }}" },
      "keyword.debug": { "color": "{{ red }}" },
      "keyword.directive": { "color": "{{ cyan }}" },
      "keyword.directive.define": { "color": "{{ cyan }}" },
      "keyword.exception": { "color": "{{ bright_magenta }}" },
      "keyword.export": { "color": "{{ blue }}" },
      "keyword.function": { "color": "{{ bright_magenta }}" },
      "keyword.import": { "color": "{{ blue }}" },
      "keyword.modifier": { "color": "{{ yellow }}" },
      "keyword.operator": { "color": "{{ bright_blue }}" },
      "keyword.repeat": { "color": "{{ bright_magenta }}" },
      "keyword.return": { "color": "{{ bright_magenta }}" },
      "keyword.type": { "color": "{{ bright_magenta }}" },
      "label": { "color": "{{ blue }}" },
      "link_text": { "color": "{{ blue }}" },
      "link_uri": { "color": "{{ blue }}" },
      "module": { "color": "{{ blue }}" },
      "namespace": { "color": "{{ blue }}" },
      "number": { "color": "{{ orange }}" },
      "number.float": { "color": "{{ orange }}" },
      "operator": { "color": "{{ bright_blue }}" },
      "parameter": { "color": "{{ cyan }}", "font_style": "italic" },
      "parent": { "color": "{{ yellow }}" },
      "predictive": { "color": "{{ dim }}", "font_style": "italic" },
      "predoc": { "color": "{{ dim }}" },
      "primary": { "color": "{{ foreground }}" },
      "property": { "color": "{{ cyan }}" },
      "punctuation": { "color": "{{ dark_foreground }}" },
      "punctuation.bracket": { "color": "{{ dark_foreground }}" },
      "punctuation.delimiter": { "color": "{{ dark_foreground }}" },
      "punctuation.list_marker": { "color": "{{ cyan }}" },
      "punctuation.special": { "color": "{{ bright_blue }}" },
      "punctuation.special.symbol": { "color": "{{ bright_blue }}" },
      "string": { "color": "{{ green }}" },
      "string.doc": { "color": "{{ green }}" },
      "string.documentation": { "color": "{{ green }}" },
      "string.escape": { "color": "{{ bright_magenta }}" },
      "string.regex": { "color": "{{ bright_cyan }}" },
      "string.regexp": { "color": "{{ bright_cyan }}" },
      "string.special": { "color": "{{ cyan }}" },
      "string.special.path": { "color": "{{ cyan }}" },
      "string.special.symbol": { "color": "{{ cyan }}" },
      "string.special.url": { "color": "{{ blue }}" },
      "symbol": { "color": "{{ cyan }}" },
      "tag": { "color": "{{ yellow }}" },
      "tag.attribute": { "color": "{{ foreground }}" },
      "tag.delimiter": { "color": "{{ dark_foreground }}" },
      "tag.doctype": { "color": "{{ dim }}" },
      "text": { "color": "{{ foreground }}" },
      "text.literal": { "color": "{{ green }}" },
      "title": { "color": "{{ blue }}", "font_weight": 700 },
      "type": { "color": "{{ yellow }}" },
      "type.builtin": { "color": "{{ foreground }}" },
      "type.class.definition": { "color": "{{ yellow }}" },
      "type.definition": { "color": "{{ yellow }}" },
      "type.interface": { "color": "{{ yellow }}" },
      "type.super": { "color": "{{ yellow }}" },
      "variable": { "color": "{{ foreground }}" },
      "variable.builtin": { "color": "{{ foreground }}", "font_style": "italic" },
      "variable.member": { "color": "{{ cyan }}" },
      "variable.parameter": { "color": "{{ cyan }}", "font_style": "italic" },
      "variable.special": { "color": "{{ foreground }}", "font_style": "italic" },
      "variant": { "color": "{{ orange }}" }
    }
  }
}
